apiVersion: v1
kind: Pod
metadata:
  name: wasm-demo
spec:
  containers:
    - name: wasm-demo
      image: dkoacr.azurecr.io/wasm-demo:v0.0.0
      command: []
  nodeName: demo
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"
  imagePullSecrets:
    - name: demo-wasi-secret